version: "3.7"
services:
  winner-system-backend:
    container_name: "winner-system-backend"
    build:
      context: .
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - "8080:8080"
    depends_on:
      posegres_db:
        condition: service_healthy
  posegres_db:
    container_name: "posegres_db"
    image: postgres:14.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
#      - POSTGRES_DB=pangea_local_dev
#      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: "unless-stopped"
    ports:
      - "5432:5432"