spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:validate}
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:create-drop}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
database:
  init: ${DATABASE_INIT:true}
  teams_data: ${TEAMS_DATA_PATH:teams.csv}
logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL:DEBUG}
      benaya:
        ai:
          winnersystem:
            factory:
              SseFactory: ${LOGGING_LEVEL:DEBUG}
            listeners:
              org.benaya.ai.winnersystem.listeners.SseEventsListener: ${LOGGING_LEVEL:DEBUG}
            service:
              impl: ${LOGGING_LEVEL:DEBUG}
UI:
  url: ${UI_URL:http://localhost:3000}
game:
  length: ${GAME_LENGTH:30}
  number_of_goal_events_per_game: ${GAME_NUM_GOAL_EVENTS:5}
  break_between_periods_in_seconds: ${GAME_BREAK_BETWEEN_PERIODS:60}
