spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:validate}
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
database:
  init: ${DATABASE_INIT:false}
  teams_data: ${TEAMS_DATA_PATH:teams.csv}
