spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:validate}
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:create-drop}
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
database:
  init: ${DATABASE_INIT:true}
  teams_data: ${TEAMS_DATA_PATH:teams.csv}
logging:
  level:
    org:
      springframework:
        security: DEBUG
      benaya:
        ai:
          winnersystem:
            service:
              impl: DEBUG
game:
  length: ${GAME_LENGTH:30}
  num_teams: ${GAME_NUM_TEAMS:10}
  number_of_goal_events_per_game: ${GAME_NUM_GOAL_EVENTS:5}
  break_between_periods_in_seconds: ${GAME_BREAK_BETWEEN_PERIODS:60}
